name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What use case does it address?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - "New file type support"
        - "CLI enhancement"
        - "API enhancement"
        - "Performance improvement"
        - "Output format"
        - "Integration"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: file-types
    attributes:
      label: File Types (if applicable)
      description: If requesting new file type support, list the specific file types, extensions, or formats
      placeholder: ".xyz files, proprietary format ABC, etc."

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        Example command:
        fft --new-option file.ext

        Expected output:
        file.ext: New Type (confidence: 95%)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? Why wouldn't they work?
      placeholder: "I considered using tool X, but..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would be helpful"
        - "Important for my workflow"
        - "Critical for my use case"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Simple (configuration change)"
        - "Moderate (new detection logic)"
        - "Complex (major architecture change)"
        - "I'm not sure"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would like to help implement this feature
          required: false
        - label: I can provide test cases or sample files
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: This feature aligns with the project's goals of file type detection
          required: true
